name: Deploy to GitHub Pages

on:
  # Chạy mỗi khi bạn push code lên nhánh 'main'
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Dùng máy ảo Ubuntu

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node 🔧
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Dùng Node.js 18

      - name: Install dependencies 📦
        run: npm install

      - name: Build 🔨
        # Chạy lệnh 'npm run build' (sẽ tạo ra thư mục 'dist')
        run: npm run build

      - name: Deploy 🚀
        # Dùng Action này để đẩy thư mục 'dist' lên nhánh 'gh-pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Báo cho nó biết thư mục build là 'dist'